const MIN_ADDRESS_LENGTH = 5;
const PHONE_LENGTH = 10;

const DEFAULT_PAGINATION_LIMIT = 6

module.exports.MIN_ADDRESS_LENGTH = MIN_ADDRESS_LENGTH;
module.exports.PHONE_LENGTH = PHONE_LENGTH;
module.exports.DEFAULT_PAGINATION_LIMIT = DEFAULT_PAGINATION_LIMIT;